title: Suturina Research Group
description: Computational Chemistry and Magnetism
show_downloads: false
theme: jekyll-theme-slate

navbar:
  - link: "index.html"
    text: "Home"
  - link: "research.html"
    text: "Research"
  - link: "publications.html"
    text: "Publications"
  - link: "people.html"
    text: "People"